update rates to use the correct underlying since chainlink is perform…
Synthetixio/synthetix-subgraph pull request #47
Opened 2020-09-23 21:41 UTC by dvd-schwrtz

…ing migrations

2020-09-24 14:56 UTC, justinjmoses commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
Shouldn't this be later - basically when they updated the aggregator a day or two ago?

2020-09-24 14:56 UTC, justinjmoses requested changes

2020-09-24 14:56 UTC, justinjmoses commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
(ibid)

2020-09-24 20:22 UTC, dvd-schwrtz commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
this contract was actually deployed before the Pollux release so I left it as the Pollux date. What do you think?

2020-09-24 20:23 UTC, dvd-schwrtz commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
https://etherscan.io/tx/0xf3e11d1a78365134b01430b770b3c931473802b0e7dbeb23d132273f689e9674

2020-09-24 20:23 UTC, dvd-schwrtz commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
this was the tx that created it

2020-09-24 20:24 UTC, dvd-schwrtz commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
same for this contract

2020-09-25 22:12 UTC, dvd-schwrtz commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10873070
Note I added startBlocks to everything so it would sync quickly for testing. These all have to be removed for the older contracts that don't have startBlocks

2020-09-28 19:14 UTC, justinjmoses commented on src/rates-mapping.ts
> +    if (event.block.number > BigInt.fromI32(10923360)) {
Hmmm- perhaps we skip this and use the `AddressResolver` to fetch `ExchangeRates`?

We'd need the ABI of `AddressResolver` and can use the address of `ReadProxyAddressResolver`. This will mean we don't have to update each time a new `ExchangeRates` is added.

2020-09-28 19:16 UTC, justinjmoses commented on subgraphs/synthetix-rates.yaml
> +      startBlock: 10773070 # Pollux release (v2.27)
I think we should use a more recent block - closer to when the upgrade occurred (to prevent a lot of duplicate entities when both are being tracked). Basically you can use a block after the original aggregator last emitted an event.

2020-09-28 19:16 UTC, justinjmoses commented on src/rates-mapping.ts
> +contractsToProxies.set(
Could you move this mapping to another file and import it for clarify? 🙏

2020-09-28 20:24 UTC, justinjmoses commented on src/contracts.ts
> +// ---------------------
Could you name this something a bit more specific - keep in mind it's really specific to the rates subgraph - it's about mapping proxies to underlyings for aggregators.

2020-09-30 16:36 UTC, dvd-schwrtz commented on src/contracts.ts
> +// ---------------------
missed this one. will definitely rename it in my next PR. would do it now but syncing would be much slower.

2020-09-30 17:28 UTC, justinjmoses commented on src/contracts.ts
> +// ---------------------
ok noted

2020-10-01 02:51 UTC, justinjmoses approved these changes

2020-10-01 02:52 UTC, merged