add volume partner tracking - daily and total fee rebates and volume
Synthetixio/synthetix-subgraph pull request #50
Opened 2020-10-02 18:35 UTC by dvd-schwrtz

…for each partner

2020-10-27 21:47 UTC, dvd-schwrtz commented on mustache/json/exchanger/rates-differences.json
> +    "startBlock": 10537958
TODO - make this file js and use a variable for common blocks

2020-10-27 21:50 UTC, dvd-schwrtz commented on create-yaml-json.js
> +const DOUBLE_ABI_CONTRACT = {
TODO add comment here for this variable and add comment for the file

2020-10-27 21:50 UTC, dvd-schwrtz commented on mustache/json/output/synthetix-exchanger.json
> +{
todo make this js and use variables for the block numbers for faster testing

2020-10-27 21:51 UTC, dvd-schwrtz commented on mustache/json/exchanger/data-sources.json
> +  {
to do use js and add block numbers as variables for faster testing

2020-11-03 20:57 UTC, justinjmoses commented on README.md
> +1. To use a single start block for all contracts within the rates or exchanger subgraph, simply change the UNIVERSAL_START_BLOCK in `package.json` from null to a number for the relevant subgraph comm
1. I think instead of env variables you should lean on `commander` and use CLI args.
2. I don't think `:test` is a good name as it implies automated testing. If you use a wrapper command that calls the `codegen` programmatically (I presume there's a way to but haven't checked), then this should be easy enough.

2020-11-03 20:58 UTC, justinjmoses commented on README.md
> +2. To modify individual contracts for the rates or exchanger subgraphs in prod or testing (it is recommended not to change the prod config unless adding new contracts), please change the `modify_star
I suggest using `json` for these as they are purely data not programmatic.

2020-11-03 21:02 UTC, justinjmoses requested changes
At a high level, this is definitely the right way to go. 

Two big things I think will help this however:
1) Use `commander` as per the suggestion and lean on `json` for configuration - it's how we organize deployment in https://github.com/Synthetixio/synthetix
2) You can use `synthetix.getVersions` with `byContract: true` to populate a lot of this information and it would be much better than hard-coding addresses where possible

2020-11-16 17:58 UTC, justinjmoses requested changes

2020-11-16 17:58 UTC, justinjmoses commented on mustache/templates/rates/set-start-blocks.js
> +    prod: 9085543,
should we not pin down these dupes somewhere?

2020-11-16 17:58 UTC, justinjmoses commented on package.json
> +    "yaml:rates": "node ./create-yaml-file create-yaml --subgraph rates --env prod --universal-test-block null && mustache mustache/yaml_output/synthetix-rates.json mustache/yaml.mustache > subgraphs
how about instead of creating and committing these files to the codebase, we output them from the create step and pipe that into the mustache process?

2020-11-17 19:47 UTC, justinjmoses approved these changes

2020-11-17 20:13 UTC, merged